# Production Docker Compose Configuration
# Uses ./rootfs for persistent storage
# External port: 172.17.0.1:64180:80 (Docker bridge network)

services:
  quotes:
    image: ghcr.io/apimgr/quotes:latest
    container_name: quotes
    restart: unless-stopped

    environment:
      - CONFIG_DIR=/config
      - DATA_DIR=/data
      - LOGS_DIR=/logs
      - PORT=80
      - ADDRESS=0.0.0.0
      - DB_PATH=/data/db/quotes.db
      # Uncomment and set for first deployment
      #- ADMIN_USER=administrator
      #- ADMIN_PASSWORD=changeme
      #- ADMIN_TOKEN=your-token-here

    volumes:
      - ./rootfs/config/quotes:/config
      - ./rootfs/data/quotes:/data
      - ./rootfs/logs/quotes:/logs

    ports:
      - "172.17.0.1:64180:80"

    networks:
      - quotes

    healthcheck:
      test: ["CMD", "/usr/local/bin/quotes", "--status"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  quotes:
    name: quotes
    external: false
    driver: bridge
